### PR TITLE
Docs: Fix permalink to Monolog log levels

### PR DESCRIPTION
**Pull request by GaryJones**

### CODE REVIEW

**Comment by bramus** [comment]
Hi @GaryJones,

I see that you link to a specific revision of the doc file, instead of the one in master (https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#log-levels). Is there a specific reason for this? I'd prefer linking to the file in master, as it'll receive content updates.

Regards,
Bramus.

**Comment by GaryJones** [comment]
> I'd prefer linking to the file in master, as it'll receive content updates.

That's exactly what you don't want.

The link I used will always work (short of the Monolog repo being deleted). _What is in that specific commit matches to what is implemented inside MCS **right now**._

If Monolog added in a new level, or changed their numbering, and updated their documentation on `master`, then, until MCS caught up, there would be a discrepancy. When MCS did catchup, then you would update this link to the Monolog commit that matched.

Likewise, if they moved their documentation (which is why this link got broken in the first place as they moved it into ` doc/` directory), then this link in the MCS documentation would still correctly link to the Monolog commit that matches what MCS has implemented.

**Comment by bramus** [comment]
Hi @GaryJones,

I've updated the readme to reflect the changes made in #56 , but kept the link to the master version of the docs.

The logic followed here is that linking to master won't necessitate an update per commit happening to monolog. Only when big changes happen to the monolog repo _(such as the docs being split off, or a new version)_, an update to this readme would be needed.

Thanks for your additions,
Bramus.

**Comment by GaryJones** [comment]
> The logic followed here is that linking to master won't necessitate an update per commit happening to monolog.

By linking directly to Monolog `master`, the MSC link is precisely at risk of breaking on each Monolog commit! Maybe they rename `doc/`, or change the numbering or title of the doc file - each of those will break the link again.

With a link that includes the commit ID, your link will still work, even if Monolog does go and fiddle with their docs in some way. The commit ID is a permalink. GitHub even has a [keyboard shortcut for getting the canonical URL](https://help.github.com/articles/getting-permanent-links-to-files/).

[This](http://andrew.yurisich.com/work/2014/07/16/dont-link-that-line-number/) post relates to use of line numbers in a non-canonical URL, but the concept is exactly the same.

Aside: now that #56 is in, the statement probably needs rewriting to include the use of named levels anyway :-)

**Pull request closed without merging**
