### PR TITLE
Tags config array

### PR DESCRIPTION
**Pull request by jamieburchell**
Possible rework for your consideration...

### CODE REVIEW

**Comment by bramus** [comment]
Hi @jamieburchell,

Great simplification of the code; Thanks!

Before merging I do want to express my doubts with the use of `if (stripos($url, 'http://') !== false) { ... }` in the code, as urls such as `https://example.com/makesecureproxy.php?source=http://example.com/insecure.jpg` will be marked as a false positive by it (the check will yield `47` as a result, yet it's no insecure URL). Perhaps it's better to check if it's `0`(viz. the given `$url` starts with `http://`)?

Curious about your stance on this.

Regards,
Bram.

**Comment by jamieburchell** [comment]
Hey!

Technically in your example:

`https://example.com/makesecureproxy.php?source=http://example.com/insecure.jpg`

should be

`https://example.com/makesecureproxy.php?source=http%3A%2F%2Fexample.com%2Finsecure.jpg`

The only reason I went with the `sripos` is because in srcset you could have:

`srcset="http://example.com/1, http://example.com/2"`

I suppose the string could be exploded by comma in to an array and then checked.

**Comment by bramus** [comment]
Point taken. We should indeed assume that querystring parameters are properly encoded, as it's a mandatory practice. 

v2.4 is coming up :-)

**Comment by jamieburchell** [comment]
Excellent. Thanks :)

**Pull request merged**
